name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  configure:
    runs-on: ubuntu-22.04
    steps:
    - name: Install boost
      id: install-boost
      uses: MarkusJx/install-boost@v2.4.4
      with:
          boost_version: 1.80.0
  
  test:
    runs-on: ubuntu-22.04
    needs: configure
    outputs:
      test-results: ${{ steps.test.outputs.test }}
    steps:
    - uses: actions/checkout@v4
    - name: build
      id: build
      run: make clean; make
      env: 
        CC: gcc-11
        CXX: g++-11
    - name: test
      id: test
      run: ./test localhost 1895 >> "$GITHUB_OUTPUT"

  output:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - env:
          result: ${{ needs.test.outputs.test-results }}
        run: echo "$result"
