name: C/C++ CI

on:
  push:
    # branches: [ "main" ] # TODO: temporarily allow on all branch pushes to validate
  pull_request:
    # branches: [ "main" ] # TODO: temporarily allow on all branch pushes to validate

jobs:
  configure:
    runs-on: ubuntu-22.04
    steps:
    - name: Install boost
      id: install-boost
      uses: MarkusJx/install-boost@v2.4.4
      with:
          boost_version: 1.80.0
          platform_version: 22.04
    - name: Configure path
      id: configure-path
      # run: export LD_LIBRARY_PATH=/opt/boost-1.80.0/lib:$LD_LIBRARY_PATH ${{github.workspace}}
      run: export LD_LIBRARY_PATH=${{github.workspace}}:$LD_LIBRARY_PATH
  
  test:
    runs-on: ubuntu-22.04
    needs: configure
    outputs:
      test-results: ${{ steps.test.outputs.test }}
    steps:
    - uses: actions/checkout@v4
    - name: build
      id: build
      run: make clean; make
      env: 
        CC: gcc-11
        CXX: g++-11
    - name: test
      id: test
      run: ./test localhost 1895 >> "$GITHUB_OUTPUT"

  output:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - env:
          result: ${{ needs.test.outputs.test-results }}
        run: echo "$result"
