name: C/C++ CI

on:
  push:
    # branches: [ "main" ] # TODO: temporarily allow on all branch pushes to validate
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BOOST_ROOT: ${{ github.workspace }}/boost

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Boost cache
      id: boost-cache
      uses: actions/cache@v3
      with:
        path: ${{ env.BOOST_ROOT }}
        key: boost-${{ runner.os }}-${{ hashFiles('**/c-cpp.yml') }}

    - name: Install Boost
      if: steps.boost-cache.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install libboost-all-dev -y
        # Move Boost files to the custom directory
        sudo mv /usr/include/boost ${{ env.BOOST_ROOT }}

    - name: Build and Test
      run: |
        # Update your build process to use the custom Boost directory
        make run BUILD=release
