name: C/C++ CI

on:
  push:
    # branches: [ "main" ] # TODO: temporarily allow on all branch pushes to validate
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Boost cache
      id: boost-cache
      uses: actions/cache@v2
      with:
        path: /usr/include/boost
        key: boost-${{ runner.os }}-${{ hashFiles('c-cpp.yml') }}
        restore-keys: |
          boost-${{ runner.os }}-

    - name: Install Boost
      if: steps.boost-cache.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install libboost-all-dev -y

    - name: Build
      run: make clean; make BUILD=release

    - name: Verify Tests
      run: |
        if ! make run | tee /dev/tty | grep -q "FAIL"; then
          echo "Tests passed!"
        else
          echo "Tests failed!"
          exit 1
        fi