name: C/C++ CI

on:
  push:
    # branches: [ "main" ] # TODO: temporarily allow on all branch pushes to validate
  pull_request:
    # branches: [ "main" ] # TODO: temporarily allow on all branch pushes to validate

jobs:
  configure:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: install boost
      id: install-boost
      uses: MarkusJx/install-boost@v2.4.4
      with:
          boost_version: 1.80.0
          platform_version: 22.04
    - name: install boost-thread
      id: install-boost-thread
      run: sudo apt install libboost-thread-dev -y
    - name: build
      id: build
      run: make clean; make
      env: 
        CC: gcc-11
        CXX: g++-11
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
  
  test:
    runs-on: ubuntu-22.04
    needs: configure
    outputs:
      test-results: ${{ steps.test.outputs.test }}
    steps:
    - name: test
      id: test
      run: ./test localhost 1895 >> "$GITHUB_OUTPUT"

  output:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - env:
          result: ${{ needs.test.outputs.test-results }}
        run: echo "$result"
